# -- Main Menu --

[[main]]
  name = "À propos"
  pageRef = "timeline/timeline"
  weight = 10

[[main]]
  name = "Recherche"
  pageRef = "research"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Livres"
  pageRef = "books"
  weight = 40

[[main]]
  name = "Étudiants"
  pageRef = "students"
  weight = 50

[[main]]
  identifier = "scholar"
  pre = "google_scholar"
  url = "https://scholar.google.com/citations?user=bcrbZrEAAAAJ&hl=fr"
  weight = 100

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/jdzucker"
  weight = 200

# -- Footer Menu --

[[footer]]
  name = "Publications"
  pageRef = "publications"
  weight = 10

[[footer]]
  name = "Recherche"
  pageRef = "research"
  weight = 20

[[footer]]
  name = "Contact"
  url = "mailto:Jean-Daniel.zucker@ird.fr"
  weight = 30
